### ISSUE TITLE
U+093D DEVANAGARI SIGN AVAGRAHA is copied from Noto Serif Devanagari

### ISSUE THREAD

**Issue by dscorbett** [notofonts/dogra#12]
### Font
NotoSerifDogra-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/dogra/releases/tag/NotoSerifDogra-v1.006
Date: 2022-10-09

### Font version
Version 1.006

### Issue
The full font copies U+093D DEVANAGARI SIGN AVAGRAHA from Noto Serif Devanagari, ignoring the glyph `Avagraha.dogra`, which presumably was designed to matched Dogra better.

Where did Google’s sample text for this font come from? It is not appropriate to use U+093D in Dogra, because all avagrahas in Unicode so far are script-specific. If Dogra-script texts really use avagraha, it should probably be encoded as a new DOGRA SIGN AVAGRAHA character. Unicode should at least be given the chance to give some advice about this character before a font starts promoting the use of one from another script.

If Google’s sample text is just some Sanskrit automatically transliterated into Dogra, I would assume it is a faulty transliteration, and I would change the text instead of the font.

### Character data
ऽ
U+093D DEVANAGARI SIGN AVAGRAHA

### Screenshots
![ऽ](https://user-images.githubusercontent.com/1124347/194786195-8757f61d-b8ef-4ffb-8b65-637871bab7bb.png)
Compare `Avagraha.dogra`:
![ऽ](https://user-images.githubusercontent.com/1124347/194786231-73f9d2b8-5501-4d36-8629-d6e060a115f1.png)

**Comment by bgo-eiu** [comment]
@dscorbett You would be correct to point out the sample text used by Google is Sanskrit, not Dogri. Avagraha is not used in the writing of Dogri in any script

**Comment by simoncozens** [comment]
What we need to fix this bug is a reasonable Dogra sample text...

**Comment by bgo-eiu** [comment]
@simoncozens https://archive.org/details/QfgG_shri-ranbir-singh-sainik-dand-vidhi-military-penal-code-jammu-1887-takri-and-urd/

Transcribing a section from this would be a good idea. (Ranbir Singh was the king who ordered the creation of the Dogra script a.k.a. Takri in the sense used here.)

**Comment by simoncozens** [comment]
We now have a Dogri sample text in the language repository (a translation of UDHR), so we don't need the (inappropriate) avagraha any more; I've removed it from the subset.

**Comment by sridatta1** [comment]
JFYI
Dogra avagraha is now accepting for encoding last year end
https://www.unicode.org/L2/L2025/25245-candrabindu-avagraha-dogra.pdf
