### ISSUE TITLE
Conjuncts with vowel sign I is rendered with Virama

### ISSUE THREAD

**Issue by sridatta1** [notofonts/dogra#9]
### Title 
Conjuncts with vowel sign I is rendered with Virama
### Font 
Noto Serif Dogra

### Where the font came from, and when
https://fonts.google.com/noto/specimen/Noto+Serif+Dogra
Date: 2022-07-01
With vowel sign I, the conjuncts are broken and are rendered with Virama
Text: 
𑠊𑠹𑠨 𑠙𑠹𑠤 𑠑𑠹𑠓 𑠩𑠹𑠔 𑠧𑠹𑠤
𑠊𑠹𑠨𑠭 𑠙𑠹𑠤𑠭 𑠑𑠹𑠓𑠭 𑠩𑠹𑠔𑠭 𑠧𑠹𑠤𑠭
![text](https://user-images.githubusercontent.com/23263723/177006963-74067f8b-79f4-48f8-9fda-b5ed76aa6ff4.png)

**Comment by simoncozens** [comment]
This is fixed in 1.006.
